apiVersion: skaffold/v1beta13
kind: Config
build:
  local:
    useBuildkit: true

  artifacts:
    - image: replicated-kurl-sh
      context: "./"
      sync:
        manual:
          - src: "src/**/*.js"
            dest: "./"
          - src: "src/**/*.jsx"
            dest: "./"
          - src: "src/**/*.png"
            dest: "./"
          - src: "src/**/*.scss"
            dest: "./"
      docker:
        dockerfile: ./Dockerfile.skaffold

deploy:
  kustomize:
    path: "./kustomize/overlays/dev"